#!/usr/bin/env python3
"""
build_artifact_registry.py — generate an artifact catalog for a project.

Answers "what artifacts exist, where, owned by whom, in what state?" — the
retrieval/discovery layer the RTM (which threads *requirements*) doesn't cover.

It reads the **docs root** (resolved from `.shipwright/config.json` → `docs_root`,
default `docs/`, falling back to the project root for a flat layout), discovers
each artifact's kind from its filename, reads owner/status/version/last-updated
from the doc header (Field/Value table, bold lines, or frontmatter), and lists
the Req-IDs each defines.

It writes the **catalog into `.shipwright/`** (derived machinery, kept out of the
human-facing docs tree):
  .shipwright/artifacts.json   machine-readable manifest (consumed by the MCP server)
  .shipwright/ARTIFACTS.md     human-readable catalog table

Dependency-free (Python 3 stdlib only); read-only except for those outputs.

Usage:
    python build_artifact_registry.py <project-root>          # default: current dir
    python build_artifact_registry.py <root> --init           # also write a default config.json
    python build_artifact_registry.py <root> --check          # exit 1 if the catalog is stale
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import rtm_core  # noqa: E402


def render_md(docs_root, arts):
    lines = [
        "# Artifacts",
        "",
        f"> Generated by `build_artifact_registry.py` from `{docs_root}/`. Do not edit — re-run. "
        f"{len(arts)} artifacts. The catalog of *what exists and where*; the RTM threads the "
        "requirements between them.",
        "",
        "| ID | Kind | Title | Path | Owner | Status | Version | Updated | Req-IDs |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for a in arts:
        lines.append(
            f"| `{a['id']}` | {a['kind']} | {a['title']} | `{a['path']}` | {a['owner'] or '—'} | "
            f"{a['status'] or '—'} | {a['version'] or '—'} | {a['updated'] or '—'} | {a['id_count']} |"
        )
    return "\n".join(lines) + "\n"


def main(argv):
    rest = argv[1:]
    check, init = "--check" in rest, "--init" in rest
    baseline, args, skip = None, [], False
    for i, a in enumerate(rest):
        if skip:
            skip = False
            continue
        if a == "--baseline" and i + 1 < len(rest):
            baseline, skip = rest[i + 1], True
        elif not a.startswith("--"):
            args.append(a)
    project_root = Path(args[0]) if args else Path(".")
    if not project_root.is_dir():
        print(f"build_artifact_registry: {project_root} is not a folder")
        return 2

    docs_root = rtm_core.resolve_docs_root(project_root)
    arts = rtm_core.artifacts(docs_root)
    sw = project_root / rtm_core.SHIPWRIGHT_DIR
    targets = {
        sw / "artifacts.json": json.dumps(arts, indent=2, ensure_ascii=False) + "\n",
        sw / "ARTIFACTS.md": render_md(docs_root, arts),
    }
    if init and not (sw / rtm_core.CONFIG_NAME).exists():
        detected = rtm_core.DEFAULT_DOCS_ROOT if (project_root / rtm_core.DEFAULT_DOCS_ROOT).is_dir() else "."
        targets[sw / rtm_core.CONFIG_NAME] = json.dumps({"docs_root": detected}, indent=2) + "\n"

    if check:
        stale = [str(p) for p, c in targets.items()
                 if not p.exists() or p.read_text(encoding="utf-8", errors="ignore") != c]
        if stale:
            print("build_artifact_registry: DRIFT — stale/missing:\n  " + "\n  ".join(stale))
            return 1
        print(f"build_artifact_registry: in sync — {len(arts)} artifacts (docs_root: {docs_root})")
        return 0

    sw.mkdir(parents=True, exist_ok=True)
    for p, c in targets.items():
        p.write_text(c, encoding="utf-8")
    kinds = sorted({a["kind"] for a in arts})
    print(f"build_artifact_registry: wrote {sw}/artifacts.json + ARTIFACTS.md — "
          f"{len(arts)} artifacts ({', '.join(kinds)}) from docs_root {docs_root}/")
    if baseline:
        bpath = sw / "baselines" / f"{baseline}.json"
        bpath.parent.mkdir(parents=True, exist_ok=True)
        snapshot = [{"id": a["id"], "kind": a["kind"], "path": a["path"],
                     "status": a["status"], "version": a["version"], "updated": a["updated"]} for a in arts]
        bpath.write_text(json.dumps({"baseline": baseline, "artifacts": snapshot}, indent=2, ensure_ascii=False) + "\n",
                         encoding="utf-8")
        print(f"  baseline: froze {len(snapshot)} artifacts (id/status/version/updated) -> {bpath}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
