#!/usr/bin/env python3
"""
build_agent_index.py — generate agents/INDEX.md from each agent's frontmatter.

Reads the machine-readable contract block (phase, outputs, id_prefix, rtm_column,
upstream, downstream, claude_code) that every agent declares per project_guides/AGENT-AUTHORING.md,
and emits a lifecycle-phase index so the funnel is navigable by *when you run it*
rather than by reading every agent file. Dependency-free (Python 3 stdlib only); read-only
except for writing agents/INDEX.md.

Usage:
    python hooks/build_agent_index.py            # from the project_managment_agents root
    python hooks/build_agent_index.py <agents-dir>

Exit 0 always (it's a generator); prints a one-line summary.
"""
import re
import sys
from pathlib import Path

PHASE_ORDER = [
    "discovery", "requirements", "design", "planning",
    "build", "test", "review", "release", "operate", "process",
]


def parse_frontmatter(text):
    """Return the frontmatter block (between the first two '---') as raw lines."""
    if not text.startswith("---"):
        return []
    end = text.find("\n---", 3)
    if end == -1:
        return []
    return text[3:end].splitlines()


def scalar(lines, key):
    for ln in lines:
        m = re.match(rf"\s*{re.escape(key)}\s*:\s*(.+?)\s*$", ln)
        if m:
            return m.group(1).strip().strip('"')
    return ""


def inline_list(lines, key):
    raw = scalar(lines, key)
    if not raw or raw in ("[]", "—"):
        return []
    raw = raw.strip("[]")
    return [x.strip().strip('"') for x in raw.split(",") if x.strip()]


def claude_cmd(lines):
    raw = scalar(lines, "claude_code")
    cmd = re.search(r"command:\s*([^,}\s]+)", raw)
    return cmd.group(1) if cmd else "—"


def main(argv):
    root = Path(argv[1]) if len(argv) > 1 else Path("agents")
    if not root.is_dir():
        root = Path("project_managment_agents/agents")
    files = sorted(p for p in root.glob("*.md") if p.name not in ("INDEX.md", "HELP.md"))

    agents = []
    for f in files:
        lines = parse_frontmatter(f.read_text(encoding="utf-8", errors="ignore"))
        if not lines:
            continue
        agents.append({
            "name": f.stem,
            "phase": scalar(lines, "phase") or "(unset)",
            "outputs": scalar(lines, "outputs") or "—",
            "id_prefix": scalar(lines, "id_prefix") or "—",
            "rtm_column": scalar(lines, "rtm_column") or "—",
            "upstream": inline_list(lines, "upstream"),
            "downstream": inline_list(lines, "downstream"),
            "command": claude_cmd(lines),
        })

    out = ["# Agent Lifecycle Index",
           "",
           "> Auto-generated by `hooks/build_agent_index.py` from each agent's `phase:` "
           "frontmatter. Do not edit by hand — re-run the generator. Navigate the fleet by "
           "*when you run it* (phase), not by theme.",
           ""]
    total = 0
    for phase in PHASE_ORDER + sorted({a["phase"] for a in agents} - set(PHASE_ORDER) - {"(unset)"}):
        group = [a for a in agents if a["phase"] == phase]
        if not group:
            continue
        out.append(f"## {phase.capitalize()}")
        out.append("")
        out.append("| Agent | Produces | ID | RTM column | Hands off to | Command |")
        out.append("|---|---|---|---|---|---|")
        for a in sorted(group, key=lambda x: x["name"]):
            ds = ", ".join(a["downstream"]) or "—"
            out.append(f"| `{a['name']}` | {a['outputs']} | {a['id_prefix']} | {a['rtm_column']} | {ds} | {a['command']} |")
        out.append("")
        total += len(group)

    # Entry points — agents that are not downstream of any other agent. These are
    # invoked directly or are always-on/foundational; an unexpected name here is an
    # orchestration gap (an agent nothing hands off to, so the flow never reaches it).
    targets = set()
    for a in agents:
        targets.update(a["downstream"])
    no_inbound = sorted(a["name"] for a in agents if a["name"] not in targets)
    if no_inbound:
        out.append("## Entry points (no inbound handoff)")
        out.append("")
        out.append("Agents that are not downstream of any other — invoked directly, or "
                   "always-on / foundational. Verify each is intentional; an unexpected name "
                   "here is an orchestration gap (nothing hands off to it).")
        out.append("")
        out.append(", ".join(f"`{n}`" for n in no_inbound))
        out.append("")

    unset = [a["name"] for a in agents if a["phase"] == "(unset)"]
    if unset:
        out.append("## (unset phase — contract block missing)")
        out.append("")
        out.append(", ".join(f"`{n}`" for n in sorted(unset)))
        out.append("")

    (root / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    print(f"build_agent_index: wrote {root / 'INDEX.md'} — {total} agents across "
          f"{len({a['phase'] for a in agents if a['phase'] != '(unset)'})} phases"
          + (f"; {len(unset)} missing contract block" if unset else "; all have contract blocks"))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
