#!/usr/bin/env python3
"""
build_help.py — generate agents/HELP.md: per-agent responsibility, when-to-run,
and copy-paste example prompts.

Single-sourced from each agent's frontmatter — responsibility from `description`,
when-to-run from `phase` + `upstream`/`downstream`, prompts from the `examples:`
field (added by add_examples.py). The retrieval/help surface for "what does this
role do and what do I type?", grouped by lifecycle phase. Dependency-free; read-only
except for writing agents/HELP.md.

Usage:
    python hooks/build_help.py [agents-dir]
"""
import re
import sys
from pathlib import Path

PHASE_ORDER = [
    "discovery", "requirements", "design", "planning",
    "build", "test", "review", "release", "operate", "process",
]


def parse_frontmatter(text):
    if not text.startswith("---"):
        return []
    end = text.find("\n---", 3)
    return text[3:end].splitlines() if end != -1 else []


def scalar(lines, key):
    for ln in lines:
        m = re.match(rf"\s*{re.escape(key)}\s*:\s*(.+?)\s*$", ln)
        if m:
            v = m.group(1).strip()
            if len(v) >= 2 and v[0] == v[-1] == "'":
                return v[1:-1].replace("''", "'")
            if len(v) >= 2 and v[0] == v[-1] == '"':
                return v[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            return v
    return ""


def inline_list(lines, key):
    raw = scalar(lines, key)
    if not raw or raw in ("[]", "—"):
        return []
    return [x.strip().strip('"') for x in raw.strip("[]").split(",") if x.strip()]


def block_list(lines, key):
    """Read a YAML block list (key:\\n  - "v"\\n  - "v")."""
    out, collecting = [], False
    for ln in lines:
        if collecting:
            s = ln.strip()
            if ln[:1] in (" ", "\t") and s.startswith("- "):
                v = s[2:].strip()
                if len(v) >= 2 and v[0] in "\"'" and v[-1] == v[0]:
                    v = v[1:-1]
                out.append(v.replace('\\"', '"').replace("\\\\", "\\"))
                continue
            break
        if ln.lstrip().startswith(key + ":"):
            collecting = True
    return out


def first_sentence(s):
    s = s.strip()
    m = re.search(r"\.\s", s)
    return (s[: m.start() + 1] if m else s).strip()


def when_to_run(up, down):
    before = "top of the funnel" if not up else "after " + ", ".join(f"`{u}`" for u in up)
    after = "" if not down else " → hands to " + ", ".join(f"`{d}`" for d in down)
    return before[0].upper() + before[1:] + after


def main(argv):
    root = Path(argv[1]) if len(argv) > 1 else Path("agents")
    if not root.is_dir():
        root = Path("project_managment_agents/agents")

    agents = []
    for f in sorted(root.glob("*.md")):
        if f.name == "HELP.md" or f.name == "INDEX.md":
            continue
        fm = parse_frontmatter(f.read_text(encoding="utf-8", errors="ignore"))
        if not fm:
            continue
        agents.append({
            "name": f.stem,
            "phase": scalar(fm, "phase") or "(unset)",
            "responsibility": first_sentence(scalar(fm, "description")),
            "upstream": inline_list(fm, "upstream"),
            "downstream": inline_list(fm, "downstream"),
            "examples": block_list(fm, "examples"),
        })

    out = ["# Agent Help — responsibilities & example prompts", "",
           "> Auto-generated by `hooks/build_help.py` from each agent's frontmatter "
           "(`description` + contract block + `examples:`). Do not edit by hand — re-run the "
           "generator. `/help-role <agent>` surfaces a single entry.", ""]
    no_examples = []
    for phase in PHASE_ORDER + sorted({a["phase"] for a in agents} - set(PHASE_ORDER)):
        group = [a for a in agents if a["phase"] == phase]
        if not group:
            continue
        out += [f"## {phase.capitalize()}", ""]
        for a in sorted(group, key=lambda x: x["name"]):
            out.append(f"### `{a['name']}`")
            out.append(f"**Owns:** {a['responsibility']}")
            out.append(f"**Run when:** {when_to_run(a['upstream'], a['downstream'])}")
            if a["examples"]:
                out.append("**Try:**")
                out += [f"- `{e}`" for e in a["examples"]]
            else:
                out.append("**Try:** _(no example prompts yet — run the examples workflow + `add_examples.py`)_")
                no_examples.append(a["name"])
            out.append("")

    (root / "HELP.md").write_text("\n".join(out), encoding="utf-8")
    msg = f"build_help: wrote {root / 'HELP.md'} — {len(agents)} agents"
    if no_examples:
        msg += f"; {len(no_examples)} missing examples: {', '.join(no_examples)}"
    print(msg)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
